### ISSUE TITLE
Lagspikes oftenly freezing players and disconnecting them.

### ISSUE THREAD

**Issue by SpooksAnno** [sunset-wasteland/sunset-wasteland#24]
Every 10 or so minutes a lagspike occurs, freezing players in place and even disconnecting other people, during a lowpop round and with pings less than 100 for those being disconnected. 
## Testmerges:
BYOND Version: 514.1583
Server revision compiled on: 2022-05-14T05:46:53+00:00
Master commit: [74abb6fe8a6f8071ef61467a8238eee8b68dd5e2](https://github.com/sunset-wasteland/sunset-wasteland/commit/74abb6fe8a6f8071ef61467a8238eee8b68dd5e2)
TGS version: 4.16.2
DMAPI version: 5.3.0

## Reproduction:

Its hard to reproduce as they vary a lot and happens out of the blue, or sometimes when examining an item. After 10 or so minutes in round (the number varying around it) a lag spike occurs for everyone in round. There used to be an image on the discord bug report, however since it was deleted its hard to keep track of it.

**Comment by SpooksAnno** [comment]
after some fumbling and games in session, was discovered that part of the lagspikes were caused by the 'spawning loadout' the magical cube a player gets whenever they spawn in. If you change tab from tab of your loadouts and download its resources, a massive dilation will occur, freezing not only the player loading it but also the entire server while attempting to download the assets.

**Comment by ExoticJazz** [comment]
That would explain why it happens more commonly towards the start of rounds, will look into that part of the code.

**Comment by ProbablyCarl** [comment]
This has been fixed for years elsewhere.
Literally just redo loadout spawning.

I can provide solutions on Discord, should you wish to reach out.

**Comment by ExoticJazz** [comment]
Update2: PR #48 lightly addresses the issue, resulting lag spikes are less lengthy but still present so it is only a half-measure solution.
